apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce
type: Opaque
stringData:
  POSTGRES_USER: ecom_user
  POSTGRES_PASSWORD: ecom_pass
  POSTGRES_DB: ecommerce
  DATABASE_URL: postgresql://ecom_user:ecom_pass@postgres-service:5432/ecommerce
  JWT_SECRET: supersecretjwtkey_change_in_production
